// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApiSqlLite.Data;

namespace TodoApiSqlLite.Migrations
{
    [DbContext(typeof(TodoContext))]
    [Migration("20201023190924_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("TodoApiSqlLite.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsComplete = true,
                            Name = "Write Backend"
                        },
                        new
                        {
                            Id = 2L,
                            IsComplete = false,
                            Name = "Write Xamarin app"
                        },
                        new
                        {
                            Id = 3L,
                            IsComplete = false,
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = 4L,
                            IsComplete = false,
                            Name = "Prepare demo"
                        },
                        new
                        {
                            Id = 5L,
                            IsComplete = false,
                            Name = "Study for examination"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
